server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-shop
    username: postgres
    password: alexey
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: pwd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    web-application-type: servlet

jwt_secret: SECRET
jwt_expirationMs: 86400000
